name: Deploy to Aliyun

on:
  push:
    branches:
      - main
      - release/*

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Aliyun Container Registry
        run: |
          echo ${{ secrets.ALIYUN_PASSWORD }} | docker login -u ${{ secrets.ALIYUN_USERNAME }} --password-stdin ${{ secrets.ALIYUN_REGISTRY }}

      - name: Build and push Docker image
        run: |
          TAG_NAME=${{ github.ref }}
          TAG_NAME=${TAG_NAME##*/}
          SHORT_SHA=$(echo ${{ github.sha }} | head -c 7)
          IMAGE_NAME=${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAMESPACES }}/${{ secrets.ALIYUN_REPO }}

          # Build and push with unique tag
          docker build -t $IMAGE_NAME:${TAG_NAME}-${SHORT_SHA} .
          docker push $IMAGE_NAME:${TAG_NAME}-${SHORT_SHA}

          # passing variables
          echo "tag_name: ${TAG_NAME}"
          echo "images_name: ${IMAGE_NAME}"

          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV
          echo "SHORT_SHA=${SHORT_SHA}" >> $GITHUB_ENV
        
        env:
          TAG_NAME: ${TAG_NAME}
          IMAGE_NAME: 

      - name: Notify server to deploy
        run: |
          IMAGE_TAG="${{ env.IMAGE_NAME }}:${{ env.TAG_NAME }}-${{ env.SHORT_SHA }}"
          echo "IMAGE_TAG: ${IMAGE_TAG}"
          curl -X POST ${{ secrets.SERVER_WEBHOOK_URL }} \
            -H 'Content-Type: application/json' \
            -d '{"image_name": "'${IMAGE_TAG}'"}'
